name: CI Pipeline with Docker Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt  # Install backend dependencies

      - name: Start Backend API
        working-directory: ./backend
        run: |
          nohup python restapi.py &  # Start the backend in the background

      - name: Wait for backend to start
        run: |
          sleep 10  # Give the backend time to start up
      # run frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install  # Install frontend dependencies

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm test  # Run frontend tests

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: test  # This ensures tests run first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # setup in github 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        working-directory: ./backend
        run: |
          docker build -t gracezheng72/backend:latest .
          docker push gracezheng72/backend:latest

      - name: Build and Push Frontend Docker Image
        working-directory: ./frontend
        run: |
          docker build -t gracezheng72/frontend:latest .
          docker push gracezheng72/frontend:latest
